### ISSUE TITLE
adminlist not matching admins

### ISSUE THREAD

**Issue by TayHemmons** [kenneththomas/ari4#9]
this line:
> if message.author in adminlist:

is not working as expected

tried a debug statement where it prints the user trying to run an admin command and also a list of the admin every time it fails

also tried doing a "not in" and the command worked, so somehow it's not matching the user with the list correctly

**Comment by kenneththomas** [comment]
yeah i tried that RIP

**Comment by kenneththomas** [comment]
ran into a similar issue while creating the logger, and realized this is because message.author is not a string.

so we do this

`strauthor = str(message.author)
`

and we basically chain that with
`def adminCheck(acrequest):
    global isAdmin
    if acrequest in AdminList:
        isAdmin = True
        print('AdminMgr: ' + acrequest + ' authorized to run admin command.')
    else:
        isAdmin = False
        print('AdminMgr: ' + acrequest + ' not authorized to run admin command.'
)
`
and an example of usage:
`    if message.content.startswith('!banword add'):
        adminCheck(strauthor)
        if isAdmin == False:
          return
        addword = message.content.split(" ")
        BannedWords.append(addword[2])
        msg = addword[2] + " added to banned words list."
        await client.send_message(message.channel, msg)
        print('BannedWordsMgr: Added ' + addword[2] + ' to banned words list.')
        print(BannedWords)
`
